#!/bin/bash

echo "Removing /var/run/* and /var/lock/*"
rm -rf /var/run/* /var/lock/*

echo "Creating new /var/run/utmp..."
touch /var/run/utmp && chmod 644 /var/run/utmp

echo "Removing possible /etc/nologin /fastboot and /forcefsck..."
rm -f /etc/nologin /fastboot /forcefsck
